name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nathanheffley/laravel-phpunit-action@master
